- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Update Apt Repository
    command: sudo apt update && apt upgrade -y 
  - name: Install Git
    command: sudo apt install git -y
  - name: Clone Repository
    ansible.builtin.git:
      repo: https://github.com/sarafabhinav1997/Medicure
      dest: /tmp/Medicure
      version: main
  - name: Apply Kubernetes manifests
    command: kubectl apply -f /tmp/Medicure/deployment.yml
    register: k8s_output
  - name: Display kubectl apply output
    debug:
    var: k8s_output.stdout_lines
