- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Update Apt Repository
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
  - name: Install Git
    ansible.builtin.apt:
      name: git
      state: present
  - name: Clone Repository
    ansible.builtin.git:
      repo: https://github.com/sarafabhinav1997/Medicure
      dest: /tmp/medicure
      version: main
  - name: Apply Kubernetes manifests
    command: kubectl apply -f /tmp/medicure/deployment.yml
    register: k8s_output
  - name: Display kubectl apply output
    debug:
    var: k8s_output.stdout_lines
