---
- name: Configure Kubernetes on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update Apt Repository
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone Repository
      git:
        repo: https://github.com/sarafabhinav1997/Medicure
        dest: /tmp/Medicure
        version: master

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /tmp/Medicure/deployment.yml
      register: kubectl_output

    - name: Display the Output of kubectl apply
      ansible.builtin.debug:
        var: kubectl_output.stdout
