- name : Configure Kubernetes on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Update Apt Repository
    command: sudo apt-get update
  - name: Install Git
    command: sudo apt-get install git -y
  - name: Clone Repository
    ansible.builtin.git:
      repo: https://github.com/sarafabhinav1997/Medicure
      dest: /tmp/Medicure
      version: main
  - name: Apply Kubernetes Deployment
    command: kubectl apply -f /tmp/Medicure/deployment.yml
    register: kubectl_output
  - name: Display the Output of kubectl apply
    debug:
      var: kubectl_output.stdout
